import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { getLangDir } from "rtl-detect";
import { NextIntlClientProvider, useLocale } from "next-intl";
import NextTopLoader from "nextjs-toploader";
import { AppBreadcrumb } from "@/components/app-breadcrumb/AppBreadcrumb";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();
  const dir = getLangDir(locale);
  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* overflow-clip */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <NextIntlClientProvider>
                <main>
                  <div className="flex  gap-5 sticky top-0  items-center backdrop-blur-xl z-50">
                    <SidebarTrigger className=" bg-primary z-10 text-white m-1 " />
                    <AppBreadcrumb className="" />
                  </div>{" "}
                  <NextTopLoader color="#00CBC1" height={5} crawl={false} />
                  {children}
                </main>
              </NextIntlClientProvider>
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

{
  /* <ThemeProvider
attribute="class"
defaultTheme="system"
enableSystem
disableTransitionOnChange
>
<SidebarProvider>
<AppSidebar />
<div className="flex-1 overflow-auto">
<SidebarTrigger />
<main className="w-full">{children}</main>
</div>
</SidebarProvider>
</ThemeProvider> */
}
